{% set name = "tango-database" %}
{% set version = "5.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/TangoDatabase/-/releases/Database-Release-{{ version }}/downloads/TangoDatabase-with-submodules-Database-Release-{{ version }}.tar.gz
  sha256: 155dea28e43bdbbd998e29c0a3d66c8671a8f7618a933d030a09673e3cc8127c

build:
  number: 0

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config              # [unix]
  host:
    - cppzmq
    - cpptango
    - mysql-devel
    - omniorb-libs
  run:
    # "lib/plugin/mysql_native_password.so" is part of mysql-client
    # it's required to connect to mariadb
    - mysql-client

test:
  commands:
    # Databaseds --help returns 255, so grep the stderr for test
    - Databaseds --help 2>&1 | grep usage                  # [unix]
    - test -f $PREFIX/share/tango/db/create_db.sql         # [unix]
    - test -f $PREFIX/share/tango/db/create_db_tables.sql  # [unix]
    - test -f $PREFIX/share/tango/db/stored_proc.sql       # [unix]
    - Databaseds.exe --help 2>&1 | findstr usage           # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango Database Server
  description: |
    This is the Tango Database server.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/TangoDatabase

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
