{% set name = "tango-database" %}
{% set version = "5.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/TangoDatabase/-/releases/Database-Release-{{ version }}/downloads/TangoDatabase-with-submodules-Database-Release-{{ version }}.tar.gz
  sha256: c36acdb7f80d108ff9a5320d879d7e17487d98188c6d3090f0d06e999d22ce98

build:
  number: 2

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config              # [unix]
  host:
    - cppzmq
    - cpptango
    # mysql_native_password authentication plugin not available in mysql 9
    # could be added: see https://github.com/conda-forge/mysql-feedstock/issues/106
    - mysql-devel <9
    - omniorb-libs

test:
  commands:
    # Databaseds --help returns 255, so grep the stderr for test
    - Databaseds --help 2>&1 | grep usage                  # [unix]
    - test -f $PREFIX/share/tango/db/create_db.sql         # [unix]
    - test -f $PREFIX/share/tango/db/create_db_tables.sql  # [unix]
    - test -f $PREFIX/share/tango/db/stored_proc.sql       # [unix]
    - Databaseds.exe --help 2>&1 | findstr usage           # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango Database Server
  description: |
    This is the Tango Database server.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/TangoDatabase

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
