schema_version: 1

context:
  version: "5.29"

recipe:
  name: tango-database-split
  version: ${{ version }}

source:
  url: https://gitlab.com/tango-controls/TangoDatabase/-/releases/Database-Release-${{ version }}/downloads/TangoDatabase-with-submodules-Database-Release-${{ version }}.tar.gz
  sha256: 5f76d7e96319f73c4f9b7dea616a879f2c7589efb60f88dedc83616c294f186b

build:
  number: 1

outputs:
  - staging:
      name: tango-database-build
    requirements:
      build:
        - cmake
        - ninja
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - if: unix
          then:
            - pkg-config
      host:
        - cppzmq
        - cpptango
        - mysql-devel
        - omniorb-libs
    build:
      script:
        file: build

  - package:
      name: tango-database
    inherit: tango-database-build
    build:
      files:
        - if: unix
          then:
            - bin/Databaseds
            - share/tango/db/**
          else:
            - Library/bin/Databaseds.exe
            - Library/share/tango/db/**
    requirements:
      run:
        # "lib/plugin/mysql_native_password.so" is part of mysql-client
        # it's required to connect to mariadb
        - mysql-client
    tests:
      - script:
          - if: unix
            then:
              # Databaseds --help returns 255, so grep the stderr for test
              - Databaseds --help 2>&1 | grep -i usage
            else:
              - Databaseds.exe --help 2>&1 | findstr /i usage
      - package_contents:
          files:
            - if: unix
              then:
                - share/tango/db/create_db.sql
                - share/tango/db/create_db_tables.sql
                - share/tango/db/stored_proc.sql
              else:
                - Library/share/tango/db/create_db.sql
                - Library/share/tango/db/create_db_tables.sql
                - Library/share/tango/db/stored_proc.sql

  - package:
      name: tango-database-dbg
    inherit:
      from: tango-database-build
      run_exports: false
    build:
      skip:
        - not linux
      dynamic_linking:
        # Prevent dbg file to be modified
        # Will raise CRC mismatch otherwise!
        binary_relocation: false
      files:
        - lib/debug/Databaseds.dbg
    requirements:
      run:
        - ${{ pin_subpackage('tango-database', exact=True) }}
    tests:
      - package_contents:
          files:
            - lib/debug/Databaseds.dbg

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango Database Server
  description: |
    This is the Tango Database server.
    Tango-Controls is a software toolkit for building control systems.
  homepage: https://www.tango-controls.org
  repository: https://gitlab.com/tango-controls/TangoDatabase

extra:
  feedstock-name: tango-database
  recipe-maintainers:
    - beenje
    - bourtemb
